/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myshopdata.view;

import com.myshopdata.controller.msdController;
import com.myshopdata.database.MSDdb;
import com.myshopdata.entity.Kategori;
import com.myshopdata.entity.Produk;
import com.myshopdata.error.kategoriException;
import com.myshopdata.error.produkException;
import com.myshopdata.event.MSDListener;
import com.myshopdata.model.TabelProdukModel;
import com.myshopdata.model.modelmyShopdata;
import com.myshopdata.service.produkDao;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ACER
 */
public class homeView extends javax.swing.JFrame implements MSDListener, ListSelectionListener {

    private AboutView about;

    private TabelProdukModel tableModel;
    private modelmyShopdata model;
    private msdController controller;
    /**
     * Creates new form homeView
     */
    public homeView() throws SQLException {
        
        
        ImageIcon img = new ImageIcon("src/com/myshopdata/img/dashboard.png");
        this.setIconImage(img.getImage());
        initComponents();
        homeView.this.getRootPane().setBorder(new LineBorder(Color.white));
        
        tableModel = new TabelProdukModel();

        model = new modelmyShopdata();
        model.setListenermsd(this);

        controller = new msdController();
        controller.setModel(model);

        tabelProduk.getSelectionModel().addListSelectionListener(this);
        tabelProduk.setModel(tableModel);

        Connection connection = MSDdb.getConnection();
        Statement s = connection.createStatement();
        String sql = "SELECT * FROM kategori";
        ResultSet r = s.executeQuery(sql);
        cbkategori.addItem("Pilih");
        while (r.next()) {
            cbkategori.addItem(r.getString("Kategori"));
        }
        r.close();
        s.close();
        
       
        
    }


  
    

    public JTextField getTxtid() {
        return txtid;
    }

    public JComboBox<String> getCbkategori() {
        return cbkategori;
    }

    public JComboBox<String> getCbukuran() {
        return cbukuran;
    }

    public JTable getTabelProduk() {
        return tabelProduk;
    }

    public JTextField getTxtharga() {
        return txtharga;
    }

    public JTextField getTxtjumlah() {
        return txtjumlah;
    }

    public JTextField getTxtkode() {
        return txtkode;
    }

    public JTextField getTxtnamabarang() {
        return txtnamabarang;
    }

    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new keeptoo.KGradientPanel();
        barpanel1 = new javax.swing.JPanel();
        btnclose = new javax.swing.JLabel();
        minimalize = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        btndata = new javax.swing.JLabel();
        btnaccount = new javax.swing.JLabel();
        btnbout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        menupanel = new keeptoo.KGradientPanel();
        btnhome2 = new javax.swing.JLabel();
        btndata1 = new javax.swing.JLabel();
        btnaccount2 = new javax.swing.JLabel();
        btnaccount3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblaction = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        cbkategori = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JLabel();
        ukuran = new javax.swing.JLabel();
        cbukuran = new javax.swing.JComboBox<>();
        txtjumlah = new javax.swing.JTextField();
        harga = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        kode = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnkategori = new keeptoo.KButton();
        accountPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        menupanel2 = new keeptoo.KGradientPanel();
        btnhome4 = new javax.swing.JLabel();
        btndata2 = new javax.swing.JLabel();
        btnaccount4 = new javax.swing.JLabel();
        btnaccount5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();
        txtPass = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barpanel1.setOpaque(false);
        barpanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barpanel1MouseDragged(evt);
            }
        });
        barpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barpanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barpanel1MousePressed(evt);
            }
        });

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/clear-button.png"))); // NOI18N
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncloseMousePressed(evt);
            }
        });

        minimalize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/minimize.png"))); // NOI18N
        minimalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimalizeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barpanel1Layout = new javax.swing.GroupLayout(barpanel1);
        barpanel1.setLayout(barpanel1Layout);
        barpanel1Layout.setHorizontalGroup(
            barpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barpanel1Layout.createSequentialGroup()
                .addGap(1439, 1439, 1439)
                .addComponent(minimalize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnclose)
                .addGap(19, 19, 19))
        );
        barpanel1Layout.setVerticalGroup(
            barpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimalize)
                    .addComponent(btnclose))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        bg.add(barpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 0, 1520, 40));

        mainPanel.setBackground(new java.awt.Color(209, 216, 224));
        mainPanel.setMaximumSize(new java.awt.Dimension(1190, 850));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(209, 216, 224));
        homepanel.setOpaque(false);

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/home (1).png"))); // NOI18N
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });

        btndata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/online-shop_1.png"))); // NOI18N
        btndata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndataMouseClicked(evt);
            }
        });

        btnaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/account_1.png"))); // NOI18N
        btnaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccountMouseClicked(evt);
            }
        });

        btnbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/info.png"))); // NOI18N
        btnbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnboutMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang di");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/msd.png"))); // NOI18N

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnaccount)
                        .addGap(173, 173, 173)
                        .addComponent(btnbout))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addComponent(btnhome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndata)))
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(290, 290, 290))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhome)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btndata, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbout)
                    .addComponent(btnaccount))
                .addGap(0, 197, Short.MAX_VALUE))
        );

        mainPanel.add(homepanel, "card2");

        dataPanel.setBackground(new java.awt.Color(209, 216, 224));

        menupanel.setOpaque(false);

        btnhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/home.png"))); // NOI18N
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome2MouseClicked(evt);
            }
        });

        btndata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/online-shop.png"))); // NOI18N
        btndata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndata1MouseClicked(evt);
            }
        });

        btnaccount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/account.png"))); // NOI18N
        btnaccount2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccount2MouseClicked(evt);
            }
        });

        btnaccount3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/about_1.png"))); // NOI18N
        btnaccount3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccount3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaccount3)
                    .addComponent(btnaccount2)
                    .addComponent(btndata1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome2))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnhome2)
                .addGap(39, 39, 39)
                .addComponent(btndata1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnaccount2)
                .addGap(45, 45, 45)
                .addComponent(btnaccount3)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(157, 163, 171));

        lblaction.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblaction.setForeground(new java.awt.Color(51, 51, 51));
        lblaction.setText("Tambah Produk");

        namabarang.setForeground(new java.awt.Color(51, 51, 51));
        namabarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namabarang.setText("Nama Barang");

        kategori.setForeground(new java.awt.Color(51, 51, 51));
        kategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kategori.setText("Kategori");

        txtnamabarang.setBackground(new java.awt.Color(255, 255, 255));
        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });

        cbkategori.setBackground(new java.awt.Color(255, 255, 255));
        cbkategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbkategoriItemStateChanged(evt);
            }
        });
        cbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkategoriActionPerformed(evt);
            }
        });

        jumlah.setForeground(new java.awt.Color(51, 51, 51));
        jumlah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlah.setText("Jumlah");

        ukuran.setForeground(new java.awt.Color(51, 51, 51));
        ukuran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ukuran.setText("Ukuran");

        cbukuran.setBackground(new java.awt.Color(255, 255, 255));
        cbukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "XXL", "XXXL", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38" }));

        txtjumlah.setBackground(new java.awt.Color(255, 255, 255));

        harga.setForeground(new java.awt.Color(51, 51, 51));
        harga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        harga.setText("Harga");

        txtharga.setBackground(new java.awt.Color(255, 255, 255));

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(153, 153, 153));
        btncancel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        kode.setForeground(new java.awt.Color(51, 51, 51));
        kode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kode.setText("Kode");

        txtkode.setBackground(new java.awt.Color(255, 255, 255));
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setBorder(null);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namabarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btncancel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnamabarang)
                            .addComponent(cbkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbukuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtjumlah)
                            .addComponent(txtharga)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblaction))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namabarang)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategori)
                    .addComponent(cbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukuran)
                    .addComponent(cbukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btncancel))
                .addGap(14, 14, 14))
        );

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode", "Nama Barang", "Kategori", "Jumlah", "Ukuran", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnubah.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(51, 255, 51));
        btntambah.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/msd.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data Produk");
        jLabel14.setEnabled(false);

        btnkategori.setText("Tambah Kategori Barang");
        btnkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(btnubah)
                            .addComponent(btnhapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(dataPanel, "card3");

        accountPanel.setBackground(new java.awt.Color(209, 216, 224));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("Account");

        kButton1.setBorder(null);
        kButton1.setText("Log Out");
        kButton1.setFont(new java.awt.Font("EngraversGothic BT", 1, 36)); // NOI18N
        kButton1.setkBorderRadius(100);
        kButton1.setkFillButton(false);
        kButton1.setkForeGround(new java.awt.Color(255, 0, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        menupanel2.setOpaque(false);

        btnhome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/home.png"))); // NOI18N
        btnhome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome4MouseClicked(evt);
            }
        });

        btndata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/online-shop.png"))); // NOI18N
        btndata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndata2MouseClicked(evt);
            }
        });

        btnaccount4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/account.png"))); // NOI18N
        btnaccount4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccount4MouseClicked(evt);
            }
        });

        btnaccount5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/about_1.png"))); // NOI18N
        btnaccount5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccount5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanel2Layout = new javax.swing.GroupLayout(menupanel2);
        menupanel2.setLayout(menupanel2Layout);
        menupanel2Layout.setHorizontalGroup(
            menupanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(menupanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaccount5)
                    .addComponent(btnaccount4)
                    .addComponent(btndata2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome4))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        menupanel2Layout.setVerticalGroup(
            menupanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnhome4)
                .addGap(39, 39, 39)
                .addComponent(btndata2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnaccount4)
                .addGap(45, 45, 45)
                .addComponent(btnaccount5)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NAMA :");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Username :");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Password :");

        txtusername.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtusername.setText("admin");

        txtPass.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPass.setText("*****");

        txtNama.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtNama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNama.setText("isiNama");

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(menupanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jLabel3))
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusername)
                            .addComponent(txtPass)
                            .addComponent(txtNama))))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtusername))
                .addGap(15, 15, 15)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(menupanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(accountPanel, "card4");

        bg.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1190, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnabled(boolean x){
        btnubah.setEnabled(x);
        btnhapus.setEnabled(x);
    }
    
    private void barpanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barpanel1MousePressed

    private void barpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel1MouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (homeView.this.getExtendedState() == MAXIMIZED_BOTH) {
                homeView.this.setExtendedState(JFrame.NORMAL);
            } else {
                homeView.this.setExtendedState(WIDTH);
            }
        }
    }//GEN-LAST:event_barpanel1MouseClicked

    private void barpanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_barpanel1MouseDragged

    private void btncloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_btncloseMousePressed

    private void btndataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndataMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(dataPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        try {
            loadDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (produkException ex) {
            Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndataMouseClicked

    private void btnaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccountMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(accountPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnaccountMouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        try {
            loginView login = new loginView();
            login.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(homepanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btndata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndata1MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(dataPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btndata1MouseClicked

    private void btnaccount2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccount2MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(accountPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnaccount2MouseClicked

    private void btnaccount3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccount3MouseClicked
        controller.btnAbout();
    }//GEN-LAST:event_btnaccount3MouseClicked

    private void btndata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndata2MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(dataPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btndata2MouseClicked

    private void btnaccount4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccount4MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(accountPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnaccount4MouseClicked

    private void btnaccount5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccount5MouseClicked
        controller.btnAbout();
    }//GEN-LAST:event_btnaccount5MouseClicked

    private void btnhome4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(homepanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnhome4MouseClicked

    private void btnhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add
        mainPanel.add(homepanel);
        mainPanel.repaint();
        mainPanel.revalidate();


    }//GEN-LAST:event_btnhome2MouseClicked

    private void btnboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnboutMouseClicked
        AboutView about = new AboutView();
        about.setVisible(true);
    }//GEN-LAST:event_btnboutMouseClicked

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        controller.deleteProduk(this);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        
        controller.updateProduk(this);
    }//GEN-LAST:event_btnubahActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void btnkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkategoriActionPerformed
        try {
            controller.btnKategori();
        } catch (SQLException ex) {
            Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (kategoriException ex) {
            Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnkategoriActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        controller.resetProduk(this);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        controller.insertProduk(this);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void cbkategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbkategoriItemStateChanged

    }//GEN-LAST:event_cbkategoriItemStateChanged

    private void cbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkategoriActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
       
    }//GEN-LAST:event_txtidActionPerformed

    private void minimalizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimalizeMousePressed
        homeView.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimalizeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, produkException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    homeView view = new homeView();

                    try {
                        view.loadDatabase();
                        view.setVisible(true);
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (produkException ex) {
                        Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(homeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel barpanel1;
    private keeptoo.KGradientPanel bg;
    private javax.swing.JLabel btnaccount;
    private javax.swing.JLabel btnaccount2;
    private javax.swing.JLabel btnaccount3;
    private javax.swing.JLabel btnaccount4;
    private javax.swing.JLabel btnaccount5;
    private javax.swing.JLabel btnbout;
    private javax.swing.JButton btncancel;
    private javax.swing.JLabel btnclose;
    private javax.swing.JLabel btndata;
    private javax.swing.JLabel btndata1;
    private javax.swing.JLabel btndata2;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome2;
    private javax.swing.JLabel btnhome4;
    private keeptoo.KButton btnkategori;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JComboBox<String> cbukuran;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel harga;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlah;
    private keeptoo.KButton kButton1;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel lblaction;
    private javax.swing.JPanel mainPanel;
    private keeptoo.KGradientPanel menupanel;
    private keeptoo.KGradientPanel menupanel2;
    private javax.swing.JLabel minimalize;
    private javax.swing.JLabel namabarang;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtPass;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JLabel txtusername;
    private javax.swing.JLabel ukuran;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(modelmyShopdata model) {
        
        txtid.setText(model.getId() + "");
        txtkode.setText(model.getKode_barang() + "");
        txtnamabarang.setText(model.getNama_barang() + "");
        cbkategori.setSelectedItem(model.getKategori() + "");
        txtjumlah.setText(model.getJumlah() + "");
        cbukuran.setSelectedItem(model.getUkuran() + "");
        txtharga.setText(model.getHarga() + "");

    }

    @Override
    public void onInsert(Produk produk) {
        tableModel.add(produk);
    }

    @Override
    public void onUpdate(Produk model) {
        int index = tabelProduk.getSelectedRow();
        tableModel.set(index, model);
    }

    @Override
    public void onDelete() {
        int index = tabelProduk.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        
        try {
            Produk model = tableModel.get(tabelProduk.getSelectedRow());
            txtid.setText(model.getId() + "");
            txtkode.setText(model.getKode_barang() + "");
            txtnamabarang.setText(model.getNama_barang() + "");
            cbkategori.setSelectedItem(model.getKategori() + "");
            txtjumlah.setText(model.getJumlah() + "");
            cbukuran.setSelectedItem(model.getUkuran() + "");
            txtharga.setText(model.getHarga() + "");

        } catch (IndexOutOfBoundsException exception) {
        }
    }

    @Override
    public void onInsert1(Kategori kategori) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void loadDatabase() throws SQLException, produkException {
        produkDao dao = MSDdb.getProdukDao();
        tableModel.setList(dao.selectAllProduk());
    }

    @Override
    public void onDeleteKategori() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
