/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myshopdata.view;

import com.myshopdata.controller.msdController;
import com.myshopdata.database.MSDdb;
import com.myshopdata.entity.Kategori;
import com.myshopdata.entity.Produk;
import com.myshopdata.error.kategoriException;
import com.myshopdata.event.MSDListener;
import com.myshopdata.impl.KategoriDaoImpl;
import com.myshopdata.model.TabelKategoriModel;
import com.myshopdata.model.modelmyShopdata;
import com.myshopdata.service.kategoriDao;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ACER
 */
public class kategoriView extends javax.swing.JFrame implements MSDListener, ListSelectionListener {

    private TabelKategoriModel tableModel;
    private modelmyShopdata model;
    private msdController controller;
    
    
    
    public kategoriView() {
        ImageIcon img = new ImageIcon("src/com/myshopdata/img/dashboard.png");
        this.setIconImage(img.getImage());
        initComponents();
        kategoriView.this.getRootPane().setBorder(new LineBorder(Color.white));
        tableModel = new TabelKategoriModel();
        
        model = new modelmyShopdata();
        model.setListenermsd(this);
        
        controller = new msdController();
        controller.setModel(model);
         
  
         
        TabelKategori.getSelectionModel().addListSelectionListener(this);
        TabelKategori.setModel(tableModel);
        
    }

    public JTextField getTxtKategori() {
        return txtKategori;
    }

    public JTable getTabelKategori() {
        return TabelKategori;
    }
    
    
    
    int xx,xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new keeptoo.KGradientPanel();
        barpanel2 = new javax.swing.JPanel();
        btnclose1 = new javax.swing.JLabel();
        btnminnimalize = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblaction = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        kode = new javax.swing.JLabel();
        txtKategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKategori = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setUndecorated(true);

        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barpanel2.setOpaque(false);
        barpanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barpanel2MouseDragged(evt);
            }
        });
        barpanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barpanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barpanel2MousePressed(evt);
            }
        });

        btnclose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/clear-button.png"))); // NOI18N
        btnclose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnclose1MousePressed(evt);
            }
        });

        btnminnimalize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/minimize.png"))); // NOI18N
        btnminnimalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnminnimalizeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barpanel2Layout = new javax.swing.GroupLayout(barpanel2);
        barpanel2.setLayout(barpanel2Layout);
        barpanel2Layout.setHorizontalGroup(
            barpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barpanel2Layout.createSequentialGroup()
                .addContainerGap(1198, Short.MAX_VALUE)
                .addComponent(btnminnimalize)
                .addGap(18, 18, 18)
                .addComponent(btnclose1)
                .addGap(14, 14, 14))
        );
        barpanel2Layout.setVerticalGroup(
            barpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnclose1)
                    .addComponent(btnminnimalize))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        bg1.add(barpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 0, 1280, 40));

        dataPanel.setBackground(new java.awt.Color(209, 216, 224));

        jPanel1.setBackground(new java.awt.Color(157, 163, 171));

        lblaction.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblaction.setForeground(new java.awt.Color(51, 51, 51));
        lblaction.setText("Tambah Kategori");

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(153, 153, 153));
        btncancel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        kode.setForeground(new java.awt.Color(51, 51, 51));
        kode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kode.setText("Nama Kategori");

        txtKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblaction)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kode)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblaction)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode)
                    .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnsimpan))
                .addGap(92, 92, 92))
        );

        TabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Kategori"
            }
        ));
        jScrollPane1.setViewportView(TabelKategori);

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(51, 255, 51));
        btntambah.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/msd.png"))); // NOI18N

        btnrefresh.setBackground(new java.awt.Color(153, 51, 255));
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data Kategori Produk");
        jLabel14.setEnabled(false);

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel14))
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrefresh))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btntambah)
                                .addComponent(btnhapus))
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnrefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))))
        );

        bg1.add(dataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 950, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclose1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose1MousePressed
        this.setVisible(false);
    }//GEN-LAST:event_btnclose1MousePressed

    private void btnminnimalizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminnimalizeMousePressed
        kategoriView.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnminnimalizeMousePressed

    private void barpanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_barpanel2MouseDragged

    private void barpanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel2MouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (kategoriView.this.getExtendedState() == MAXIMIZED_BOTH) {
                kategoriView.this.setExtendedState(JFrame.NORMAL);
            } else {
                kategoriView.this.setExtendedState(WIDTH);
            }
        }
    }//GEN-LAST:event_barpanel2MouseClicked

    private void barpanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barpanel2MousePressed

    private void txtKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       controller.deleteKategori(this);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        controller.insertKategori(this);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        controller.resetKategori(this);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws SQLException, kategoriException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kategoriView view = new kategoriView();
                try {
                    view.loadDatabase();
                    view.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(kategoriView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (kategoriException ex) {
                    Logger.getLogger(kategoriView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelKategori;
    private javax.swing.JPanel barpanel2;
    private keeptoo.KGradientPanel bg1;
    private javax.swing.JButton btncancel;
    private javax.swing.JLabel btnclose1;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel btnminnimalize;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel lblaction;
    private javax.swing.JTextField txtKategori;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(modelmyShopdata model) {
        txtKategori.setText(model.getKategori1()+"");
    }


    @Override
    public void onInsert1(Kategori kategori) {
        tableModel.add(kategori);
    }

    @Override
    public void onDeleteKategori() {
        int index = TabelKategori.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Kategori model  = tableModel.get(TabelKategori.getSelectedRow());
            txtKategori.setText(model.getKategori()+"");
            
        } catch (IndexOutOfBoundsException exception) {
        }
    }
    
    public void loadDatabase() throws SQLException, kategoriException{
        kategoriDao dao = MSDdb.getKategoriDao();
        tableModel.setList(dao.selectAllKategori());
    }

    @Override
    public void onInsert(Produk produk) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onUpdate(Produk model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onDelete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
